api_key: Your-API-Key
leap_year: 'false'
#intervall in minutes 30 and 60 are possible
interval: 30
utc: 'true'
full_name: FirstName+LastName
reason: Your+Reason
affiliation: Your+Affiliation
email: YourEmailAdress
mailing_list: 'false'